### ISSUE TITLE
Menores correcciones al libro de ANLE

### ISSUE THREAD

**Issue by JoaquinViera** [ONSAS/libroANLE#20]
1. Ec (1.21) quitar un paréntesis "-( **(** f(xk) ...".
2. Idem al punto 1 para la Ec (1.23)
3. Pag 15 "La condición de matriz secante no es suficiente para **definir la** completamente.
4. 2.1.2 Axioma 2 - quitar V(q) **es**
5. Bifuración simétrica estable: a carga aunque sea con grandes **deformaciones**. Debería ser desplazamientos?
5. Ec (2.26) Falta cerrar elparéntisis al escribir el desp. u
6. Ec (2.44) creo que debería ser sigma_G y no sigma_E
7. Previo a Ec (2.76) "... por vectores fila, **es** decir, ..."
8. Ec (2.85) falta el traspuesto al delta_u

**Comment by jorgepz** [comment]
Genial!! Gracias. Si querés hacer el PR bienvenue!

**Comment by JoaquinViera** [comment]
La macaneé, subí directo al main sin crear una branch y PR

**Comment by jorgepz** [comment]
excelente joaquín. no hay problema, ya revisé los cambios en el commit https://github.com/ONSAS/libroANLE/commit/08417688e8c95e6afc4385e593c791c5adf140b9
